package com.example.e_orders

enum class Language { EL, EN }

object Strings {
    var current: Language = Language.EL

    val selectTable get() = when (current) { Language.EL -> "Επιλογή Τραπεζιού"; Language.EN -> "Select Table" }
    val adminPanel get() = when (current) { Language.EL -> "Πίνακας Διαχείρισης"; Language.EN -> "Admin Panel" }
    val back get() = when (current) { Language.EL -> "Πίσω"; Language.EN -> "Back" }
    val login get() = when (current) { Language.EL -> "Σύνδεση"; Language.EN -> "Login" }
    val logout get() = when (current) { Language.EL -> "Αποσύνδεση"; Language.EN -> "Logout" }
    val username get() = when (current) { Language.EL -> "Όνομα χρήστη"; Language.EN -> "Username" }
    val password get() = when (current) { Language.EL -> "Κωδικός"; Language.EN -> "Password" }
    val wrongCredentials get() = when (current) { Language.EL -> "Λάθος στοιχεία"; Language.EN -> "Wrong credentials" }
    val cancel get() = when (current) { Language.EL -> "Ακύρωση"; Language.EN -> "Cancel" }
    val save get() = when (current) { Language.EL -> "Αποθήκευση"; Language.EN -> "Save" }
    val delete get() = when (current) { Language.EL -> "Διαγραφή"; Language.EN -> "Delete" }
    val edit get() = when (current) { Language.EL -> "Επεξεργασία"; Language.EN -> "Edit" }
    val add get() = when (current) { Language.EL -> "Προσθήκη"; Language.EN -> "Add" }
    val name get() = when (current) { Language.EL -> "Όνομα"; Language.EN -> "Name" }
    val price get() = when (current) { Language.EL -> "Τιμή"; Language.EN -> "Price" }
    val category get() = when (current) { Language.EL -> "Κατηγορία"; Language.EN -> "Category" }
    val products get() = when (current) { Language.EL -> "Προϊόντα"; Language.EN -> "Products" }
    val options get() = when (current) { Language.EL -> "Επιλογές"; Language.EN -> "Options" }
    val tables get() = when (current) { Language.EL -> "Τραπέζια"; Language.EN -> "Tables" }
    val history get() = when (current) { Language.EL -> "Ιστορικό"; Language.EN -> "History" }
    val statistics get() = when (current) { Language.EL -> "Στατιστικά"; Language.EN -> "Statistics" }
    val users get() = when (current) { Language.EL -> "Χρήστες"; Language.EN -> "Users" }
    val newProduct get() = when (current) { Language.EL -> "Νέο Προϊόν"; Language.EN -> "New Product" }
    val addProduct get() = when (current) { Language.EL -> "Προσθήκη Προϊόντος"; Language.EN -> "Add Product" }
    val addCategory get() = when (current) { Language.EL -> "Προσθήκη Κατηγορίας"; Language.EN -> "Add Category" }
    val newCategory get() = when (current) { Language.EL -> "Νέα Κατηγορία"; Language.EN -> "New Category" }
    val renameCategory get() = when (current) { Language.EL -> "Μετονομασία Κατηγορίας"; Language.EN -> "Rename Category" }
    val deleteCategory get() = when (current) { Language.EL -> "Διαγραφή Κατηγορίας"; Language.EN -> "Delete Category" }
    val deleteCategoryConfirm get() = when (current) { Language.EL -> "Θέλετε να διαγράψετε"; Language.EN -> "Do you want to delete" }
    val productsWillBeDeleted get() = when (current) { Language.EL -> "προϊόντα θα διαγραφούν!"; Language.EN -> "products will be deleted!" }
    val noOptions get() = when (current) { Language.EL -> "Δεν υπάρχουν επιλογές — μόνο ποσότητα & σχόλια"; Language.EN -> "No options — only quantity & notes" }
    val addOption get() = when (current) { Language.EL -> "Προσθήκη Επιλογής"; Language.EN -> "Add Option" }
    val newOption get() = when (current) { Language.EL -> "Νέα Επιλογή"; Language.EN -> "New Option" }
    val editOption get() = when (current) { Language.EL -> "Επεξεργασία Επιλογής"; Language.EN -> "Edit Option" }
    val optionName get() = when (current) { Language.EL -> "Όνομα (π.χ. Ζάχαρη)"; Language.EN -> "Name (e.g. Sugar)" }
    val choices get() = when (current) { Language.EL -> "Επιλογές:"; Language.EN -> "Choices:" }
    val newChoice get() = when (current) { Language.EL -> "Νέα επιλογή"; Language.EN -> "New choice" }
    val addTable get() = when (current) { Language.EL -> "Προσθήκη Τραπεζιού"; Language.EN -> "Add Table" }
    val newTable get() = when (current) { Language.EL -> "Νέο Τραπέζι"; Language.EN -> "New Table" }
    val renameTable get() = when (current) { Language.EL -> "Μετονομασία Τραπεζιού"; Language.EN -> "Rename Table" }
    val empty get() = when (current) { Language.EL -> "Κενό"; Language.EN -> "Empty" }
    val draft get() = when (current) { Language.EL -> "Πρόχειρο"; Language.EN -> "Draft" }
    val sent get() = when (current) { Language.EL -> "Στάλθηκε"; Language.EN -> "Sent" }
    val quantity get() = when (current) { Language.EL -> "Ποσότητα:"; Language.EN -> "Quantity:" }
    val notes get() = when (current) { Language.EL -> "Σχόλια:"; Language.EN -> "Notes:" }
    val notesPlaceholder get() = when (current) { Language.EL -> "π.χ. χωρίς αφρόγαλα, με πάγο..."; Language.EN -> "e.g. no foam, with ice..." }
    val total get() = when (current) { Language.EL -> "Σύνολο:"; Language.EN -> "Total:" }
    val view get() = when (current) { Language.EL -> "Προβολή"; Language.EN -> "View" }
    val sendToBar get() = when (current) { Language.EL -> "Αποστολή στο Bar"; Language.EN -> "Send to Bar" }
    val sendNew get() = when (current) { Language.EL -> "Αποστολή Νέων"; Language.EN -> "Send New" }
    val send get() = when (current) { Language.EL -> "Αποστολή"; Language.EN -> "Send" }
    val order get() = when (current) { Language.EL -> "Παραγγελία"; Language.EN -> "Order" }
    val close get() = when (current) { Language.EL -> "Κλείσιμο"; Language.EN -> "Close" }
    val transferTable get() = when (current) { Language.EL -> "Μεταφορά Τραπεζιού"; Language.EN -> "Transfer Table" }
    val transferFrom get() = when (current) { Language.EL -> "Μεταφορά από"; Language.EN -> "Transfer from" }
    val to get() = when (current) { Language.EL -> "σε:"; Language.EN -> "to:" }
    val noAvailableTables get() = when (current) { Language.EL -> "Δεν υπάρχουν διαθέσιμα τραπέζια"; Language.EN -> "No available tables" }
    val splitBill get() = when (current) { Language.EL -> "Διαχωρισμός Λογαριασμού"; Language.EN -> "Split Bill" }
    val equalParts get() = when (current) { Language.EL -> "Ίσα μέρη"; Language.EN -> "Equal parts" }
    val perProduct get() = when (current) { Language.EL -> "Ανά προϊόν"; Language.EN -> "Per product" }
    val numberOfPeople get() = when (current) { Language.EL -> "Αριθμός ατόμων:"; Language.EN -> "Number of people:" }
    val eachPersonPays get() = when (current) { Language.EL -> "Κάθε άτομο πληρώνει:"; Language.EN -> "Each person pays:" }
    val selectProducts get() = when (current) { Language.EL -> "Πατήστε τα προϊόντα για να τα επιλέξετε:"; Language.EN -> "Tap products to select:" }
    val selected get() = when (current) { Language.EL -> "Επιλεγμένα:"; Language.EN -> "Selected:" }
    val remaining get() = when (current) { Language.EL -> "Υπόλοιπο:"; Language.EN -> "Remaining:" }
    val paymentMethod get() = when (current) { Language.EL -> "Τρόπος Πληρωμής"; Language.EN -> "Payment Method" }
    val cash get() = when (current) { Language.EL -> "Μετρητά"; Language.EN -> "Cash" }
    val card get() = when (current) { Language.EL -> "Κάρτα"; Language.EN -> "Card" }
    val noHistory get() = when (current) { Language.EL -> "Δεν υπάρχει ιστορικό"; Language.EN -> "No history" }
    val orderHistory get() = when (current) { Language.EL -> "Ιστορικό Παραγγελιών"; Language.EN -> "Order History" }
    val payment get() = when (current) { Language.EL -> "Πληρωμή:"; Language.EN -> "Payment:" }
    val salesStatistics get() = when (current) { Language.EL -> "Στατιστικά Πωλήσεων"; Language.EN -> "Sales Statistics" }
    val totalRevenue get() = when (current) { Language.EL -> "Συνολικά Έσοδα"; Language.EN -> "Total Revenue" }
    val orders get() = when (current) { Language.EL -> "Παραγγελίες"; Language.EN -> "Orders" }
    val average get() = when (current) { Language.EL -> "Μέσος Όρος"; Language.EN -> "Average" }
    val closeShift get() = when (current) { Language.EL -> "Κλείσιμο Βάρδιας"; Language.EN -> "Close Shift" }
    val shiftSummary get() = when (current) { Language.EL -> "Σύνοψη Βάρδιας:"; Language.EN -> "Shift Summary:" }
    val perCategory get() = when (current) { Language.EL -> "Ανά κατηγορία:"; Language.EN -> "Per category:" }
    val historyWillReset get() = when (current) { Language.EL -> "Το ιστορικό και τα στατιστικά θα μηδενιστούν!"; Language.EN -> "History and statistics will be reset!" }
    val topProducts get() = when (current) { Language.EL -> "🏆 Top 10 Προϊόντα"; Language.EN -> "🏆 Top 10 Products" }
    val salesByCategory get() = when (current) { Language.EL -> "📊 Πωλήσεις ανά Κατηγορία"; Language.EN -> "📊 Sales by Category" }
    val noDataYet get() = when (current) { Language.EL -> "Δεν υπάρχουν δεδομένα ακόμα.\nΚλείστε παραγγελίες για να δείτε στατιστικά."; Language.EN -> "No data yet.\nClose orders to see statistics." }
    val pcs get() = when (current) { Language.EL -> "τεμ."; Language.EN -> "pcs" }
    val addUser get() = when (current) { Language.EL -> "Προσθήκη Χρήστη"; Language.EN -> "Add User" }
    val newUser get() = when (current) { Language.EL -> "Νέος Χρήστης"; Language.EN -> "New User" }
    val editUser get() = when (current) { Language.EL -> "Επεξεργασία Χρήστη"; Language.EN -> "Edit User" }
    val role get() = when (current) { Language.EL -> "Ρόλος"; Language.EN -> "Role" }
    val admin get() = when (current) { Language.EL -> "Διαχειριστής"; Language.EN -> "Admin" }
    val waiter get() = when (current) { Language.EL -> "Σερβιτόρος"; Language.EN -> "Waiter" }
    val language get() = when (current) { Language.EL -> "Γλώσσα"; Language.EN -> "Language" }
    val greek get() = when (current) { Language.EL -> "Ελληνικά"; Language.EN -> "Greek" }
    val english get() = when (current) { Language.EL -> "Αγγλικά"; Language.EN -> "English" }
    val settings get() = when (current) { Language.EL -> "Ρυθμίσεις"; Language.EN -> "Settings" }
    val cantDeleteLastAdmin get() = when (current) { Language.EL -> "Δεν μπορείτε να διαγράψετε τον τελευταίο admin!"; Language.EN -> "Cannot delete the last admin!" }
}
